# This is a basic workflow to help you get started with Actions

name: Spinnaker Pre Install
env:
  SPINNAKER_VERSION: 1.24.4
  REGISTRY_URL: "gcr.io/spinnaker-marketplace/"
  NEW_REGISTRY_URL: "registry.cn-beijing.aliyuncs.com/spinnaker-cd/"
  NEW_REGISTRY_URL2: "docker.io/spinnakercd/"
  TAG_FILE: "tagfile.txt"
  BOM_DIR: ".boms"

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      
    ##
#     - name: 01-安装Halyard部署工具
#       run: |
#         chmod +x ./InstallHalyard.sh
#         ls 
#         sleep 2
#         sudo bash -x InstallHalyard.sh --user runner -y
#         sleep 5
#         hal -v    
#     ## 
    - name: 01-使用Halyard获取bom版本文件
      run: |
        
		docker login --username={{ secrets.DOCKER_USER}} -p {{ secrets.DOCKER_PASSWD}} registry.cn-beijing.aliyuncs.com
		docker pull us-docker.pkg.dev/spinnaker-community/docker/clouddriver:7.3.3-20210322155326
		docker tag us-docker.pkg.dev/spinnaker-community/docker/clouddriver:7.3.3-20210322155326 registry.cn-beijing.aliyuncs.com/jyh_docker/clouddriver:7.3.3-20210322155326 

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/clouddriver:7.3.3-20210322155326 



		docker pull us-docker.pkg.dev/spinnaker-community/docker/deck:3.6.1-20210329201325
		docker tag us-docker.pkg.dev/spinnaker-community/docker/deck:3.6.1-20210329201325 registry.cn-beijing.aliyuncs.com/jyh_docker/deck:3.6.1-20210329201325 

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/deck:3.6.1-20210329201325 




		docker pull us-docker.pkg.dev/spinnaker-community/docker/echo:2.16.0-20210208200018
		docker tag us-docker.pkg.dev/spinnaker-community/docker/echo:2.16.0-20210208200018 registry.cn-beijing.aliyuncs.com/jyh_docker/echo:2.16.0-20210208200018 

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/echo:2.16.0-20210208200018 




		docker pull us-docker.pkg.dev/spinnaker-community/docker/front50:0.26.2-20210216140019
		docker tag us-docker.pkg.dev/spinnaker-community/docker/front50:0.26.2-20210216140019 registry.cn-beijing.aliyuncs.com/jyh_docker/front50:0.26.2-20210216140019 

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/front50:0.26.2-20210216140019 



		docker pull us-docker.pkg.dev/spinnaker-community/docker/gate:1.21.0-20210215200018
		docker tag us-docker.pkg.dev/spinnaker-community/docker/gate:1.21.0-20210215200018 registry.cn-beijing.aliyuncs.com/jyh_docker/gate:1.21.0-20210215200018

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/gate:1.21.0-20210215200018




		docker pull us-docker.pkg.dev/spinnaker-community/docker/orca:2.19.0-20210209140018
		docker tag us-docker.pkg.dev/spinnaker-community/docker/orca:2.19.0-20210209140018 registry.cn-beijing.aliyuncs.com/jyh_docker/orca:2.19.0-20210209140018

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/orca:2.19.0-20210209140018




		docker pull us-docker.pkg.dev/spinnaker-community/docker/rosco:0.24.0-20210210110018
		docker tag us-docker.pkg.dev/spinnaker-community/docker/rosco:0.24.0-20210210110018 registry.cn-beijing.aliyuncs.com/jyh_docker/rosco:0.24.0-20210210110018

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/rosco:0.24.0-20210210110018




		docker pull us-docker.pkg.dev/spinnaker-community/redis/redis-cluster:v2
		docker tag us-docker.pkg.dev/spinnaker-community/redis/redis-cluster:v2 registry.cn-beijing.aliyuncs.com/jyh_docker/redis-cluster:v2

		docker push registry.cn-beijing.aliyuncs.com/jyh_docker/redis-cluster:v2
        
  
